# Generated by Django 3.0 on 2025-02-10 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='post',
            new_name='state',
        ),
    ]
